// build_pages.js
// يبني data/page_juz_map.js: خرائط gid → {page, juz} للمصحف الحفص.
// مصدران موثوقان بدون مفتاح:
//   - alquran.cloud /juz/{n}  → بدايات الأجزاء (30 طلب صغير). number == gid لدينا.
//   - quranpedia /v1/mushafs/1 → page_number لكل آية (طلب واحد). id == gid لدينا.
// شغّل: node build_pages.js
// ponytail: one-time build, ships a static map; no runtime network dependency.

const fs = require('fs');

const ALCLOUD = 'https://api.alquran.cloud/v1/juz/';
const QURANPEDIA = 'https://api.quranpedia.net/v1/mushafs/1';
const OUT = './data/page_juz_map.js';

async function fetchJson(url) {
  const r = await fetch(url);
  if (!r.ok) throw new Error(`HTTP ${r.status} for ${url}`);
  return r.json();
}

async function getJuzStartGids() {
  // خذ أول آية في كل جزء؛ حقل number = التسلسل العالمي = gid.
  const starts = [null]; // index 0 unused, juz 1..30
  for (let n = 1; n <= 30; n++) {
    const d = await fetchJson(ALCLOUD + n);
    const ayahs = d.data.ayahs;
    if (!ayahs || !ayahs.length) throw new Error(`juz ${n} empty`);
    const startGid = ayahs[0].number;
    starts.push(startGid);
  }
  // تحقّق: البدايات متصاعدة وأولها 1.
  if (starts[1] !== 1) throw new Error(`juz 1 should start at gid 1, got ${starts[1]}`);
  for (let n = 2; n <= 30; n++) {
    if (starts[n] <= starts[n - 1]) throw new Error(`non-monotonic juz start at juz ${n}`);
  }
  return starts;
}

async function getGidToPage() {
  // مصحف حفص كامل: iterate surahs → ayahs; id == gid, page_number == page.
  const d = await fetchJson(QURANPEDIA);
  const mushaf = d.data || d; // quranpedia returns mushaf at top level, no .data wrapper
  const map = {};
  let maxPage = 0;
  mushaf.surahs.forEach(s => {
    s.ayahs.forEach(a => {
      const gid = a.id;
      const page = a.page_number;
      if (typeof gid !== 'number' || typeof page !== 'number') {
        throw new Error(`bad entry surah ${s.id} ayah ${a.number}: ${JSON.stringify(a).slice(0,120)}`);
      }
      map[gid] = page;
      if (page > maxPage) maxPage = page;
    });
  });
  return { map, maxPage };
}

function juzOf(gid, juzStartGids) {
  // أكبر جزء بدايته ≤ gid.
  for (let n = 30; n >= 1; n--) if (gid >= juzStartGids[n]) return n;
  return 1;
}

(async () => {
  console.log('Fetching juz starts (alquran.cloud)…');
  const juzStartGids = await getJuzStartGids();
  console.log('  juz starts:', juzStartGids.slice(1).join(','));

  console.log('Fetching full mushaf pages (quranpedia)…');
  const { map: gidToPage, maxPage } = await getGidToPage();
  console.log('  verses:', Object.keys(gidToPage).length, 'maxPage:', maxPage);

  const byGid = {};
  let missing = 0;
  for (let gid = 1; gid <= 6236; gid++) {
    const page = gidToPage[gid];
    if (!page) { missing++; continue; }
    byGid[gid] = { page, juz: juzOf(gid, juzStartGids) };
  }
  if (missing) console.warn(`  WARN: ${missing} gids missing a page`);

  const fileContent =
    '// GENERATED by build_pages.js — do not edit by hand.\n' +
    '// ponytail: static gid→{page,juz} map for Hafs mushaf. Rebuild via: node build_pages.js\n' +
    'window.pageJuzMap = ' + JSON.stringify({
      juzStartGids,
      totalPages: maxPage,
      byGid
    }) + ';\n';

  fs.writeFileSync(OUT, fileContent, 'utf8');
  console.log(`Wrote ${OUT} (${Object.keys(byGid).length} entries).`);
})().catch(e => { console.error('BUILD FAILED:', e); process.exit(1); });
