// scripts/vendor_fonts.js
// Downloads Google Fonts as local .woff2 subsets and emits a local @font-face
// stylesheet, so the app has ZERO runtime network dependency (ADR-0004).
// Usage: node scripts/vendor_fonts.js
//
// Reusable: add families to FAMILIES below. Round 1 vendors Cairo (glass UI)
// and IBM Plex Sans Arabic (sukun UI). Amiri Quran is already vendored separately.

const { execFileSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const OUT_DIR = path.join(ROOT, 'assets', 'fonts');

// family key (for filenames) => { query: Google css2 family query, display: CSS font-family name }
const FAMILIES = {
  Cairo:             { query: 'Cairo:wght@400;600;700;800',                    display: 'Cairo' },
  IBMPlexSansArabic: { query: 'IBM+Plex+Sans+Arabic:wght@400;500;600;700',     display: 'IBM Plex Sans Arabic' },
  ReemKufi:          { query: 'Reem+Kufi:wght@500;600;700',                     display: 'Reem Kufi' },
  ReadexPro:         { query: 'Readex+Pro:wght@400;500;600;700',               display: 'Readex Pro' },
  ElMessiri:         { query: 'El+Messiri:wght@500;600;700',                   display: 'El Messiri' },
  Tajawal:           { query: 'Tajawal:wght@400;500;700',                      display: 'Tajawal' },
  NotoKufiArabic:    { query: 'Noto+Kufi+Arabic:wght@400;500;600;700;800',       display: 'Noto Kufi Arabic' },
  ArefRuqaa:         { query: 'Aref+Ruqaa:wght@400;700',                        display: 'Aref Ruqaa' },
};

// Subsets worth keeping. This is an Arabic-RTL app: latinext / cyrillicext are
// never rendered, so skip them to keep the bundle lean.
const KEEP_SUBSETS = new Set(['arabic', 'latin']);

const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36';

// curl works in this env (node https does not — IPv6/routing). Silent, file-less.
function fetchText(url) {
  return execFileSync('curl', ['-s', '--max-time', '20', '-A', UA, url], { maxBuffer: 20 * 1024 * 1024 }).toString('utf8');
}
function fetchBin(url, dest) {
  execFileSync('curl', ['-s', '--max-time', '40', '-A', UA, '-o', dest, url]);
}

// parse @font-face blocks out of Google's CSS. The subset comment (`/* arabic */`)
// PRECEDES each block, so we capture it along with the block.
const FACE_RE = /(?:\/\* ([^*]+) \*\/\s*)?@font-face\s*\{([^}]*)\}/g;
function parseFaces(css) {
  const faces = [];
  let m;
  while ((m = FACE_RE.exec(css))) {
    const subset = (m[1] || 'all').trim();
    const body = m[2];
    const get = re => { const r = body.match(re); return r ? r[1] : null; };
    const src = get(/src:\s*url\(([^)]+)\)/);
    if (!src) continue;
    faces.push({
      family: get(/font-family:\s*['"]?([^;'"]+)['"]?/),
      weight: get(/font-weight:\s*(\d+)/),
      style: get(/font-style:\s*(\w+)/) || 'normal',
      display: get(/font-display:\s*(\w+)/) || 'swap',
      unicodeRange: get(/unicode-range:\s*([^;]+);/),
      src: src.replace(/\\$/, ''),
      subset,
    });
  }
  return faces.filter(f => KEEP_SUBSETS.has(f.subset));
}

const slug = s => s.replace(/[^a-zA-Z0-9]/g, '');

(() => {
  if (!fs.existsSync(OUT_DIR)) fs.mkdirSync(OUT_DIR, { recursive: true });
  const emitted = [];
  for (const [key, entry] of Object.entries(FAMILIES)) {
    const url = `https://fonts.googleapis.com/css2?family=${entry.query}&display=swap`;
    process.stdout.write(`fetching ${key} ... `);
    const css = fetchText(url);
    const faces = parseFaces(css);
    console.log(`${faces.length} faces`);
    for (const f of faces) {
      const fname = `${key}-${f.weight}${f.style === 'italic' ? 'i' : ''}-${slug(f.subset)}.woff2`;
      const fpath = path.join(OUT_DIR, fname);
      if (!fs.existsSync(fpath)) {
        process.stdout.write(`  dl ${fname} ... `);
        fetchBin(f.src, fpath);
        console.log(`${(fs.statSync(fpath).size / 1024).toFixed(0)}KB`);
      }
      emitted.push({ ...f, key, family: entry.display, file: fname });
    }
  }

  // Emit assets/fonts/fonts.css with LOCAL @font-face declarations.
  const lines = [
    '/* AUTO-GENERATED by scripts/vendor_fonts.js. Local @font-face for vendored Google Fonts.',
    '   No runtime network dependency. Re-run after changing FAMILIES. */',
    '',
  ];
  for (const f of emitted) {
    lines.push('@font-face {');
    lines.push(`  font-family: '${f.family}';`);
    lines.push(`  font-style: ${f.style};`);
    lines.push(`  font-weight: ${f.weight};`);
    if (f.unicodeRange) lines.push(`  unicode-range: ${f.unicodeRange.trim()};`);
    lines.push(`  font-display: swap;`);
    lines.push(`  src: url('./${f.file}') format('woff2');`);
    lines.push('}');
    lines.push('');
  }
  fs.writeFileSync(path.join(OUT_DIR, 'fonts.css'), lines.join('\n'));
  console.log(`\nwrote assets/fonts/fonts.css (${emitted.length} @font-face)`);
  console.log('vendored families:', Object.keys(FAMILIES).join(', '));
})();

